name: checks
on:
  - push
  - pull_request
  - workflow_call

jobs:
  test:
    uses: vinejs/.github/.github/workflows/test.yml@main

  lint:
    uses: vinejs/.github/.github/workflows/lint.yml@main

  typecheck:
    uses: vinejs/.github/.github/workflows/typecheck.yml@main
